# Building a Regression MLP sing the Sequential API

In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

First, let's download the California Housing dataset from a direct URL. We'll use `wget` for this.

In [3]:
import requests

url = "https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv"
output_path = "housing.csv"

response = requests.get(url)
response.raise_for_status()  # Raise an exception for HTTP errors

with open(output_path, "wb") as f:
    f.write(response.content)

print(f"Downloaded {output_path}")

Downloaded housing.csv

In [4]:
housing = pd.read_csv('housing.csv')
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [5]:
housing.drop(columns="ocean_proximity", axis=1, inplace=True)

In [6]:
housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
dtype: int64

In [7]:
housing.dropna(axis=0, inplace=True)

In [8]:
housing.duplicated().sum()

np.int64(0)

In [9]:
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

Now that the `housing.csv` file is downloaded, we can load it into a pandas DataFrame.

## Train Test Split

In [10]:
X_train_full, X_test,y_train_full, y_test = train_test_split(housing.drop('median_house_value', axis=1), housing['median_house_value'], random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [20]:
scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(np.array(y_train).reshape(-1, 1))
y_valid = scaler_y.transform(np.array(y_valid).reshape(-1, 1))
y_test = scaler_y.transform(np.array(y_test).reshape(-1, 1))

## Using the Sequential API To Build, Train and Evaluate

In [21]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
from tensorflow.keras.optimizers import Adam

# Default is usually 0.001. Try 0.0001 or 0.00001
opt = Adam(learning_rate=0.0001)

In [23]:
model.compile(loss="mse", optimizer=opt, metrics=["mse"])
history = model.fit(X_train, y_train, epochs=20, validation_data=(X_valid, y_valid))

Epoch 1/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.1451 - mse: 1.1451 - val_loss: 0.7949 - val_mse: 0.7949
Epoch 2/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.7196 - mse: 0.7196 - val_loss: 0.5701 - val_mse: 0.5701
Epoch 3/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5751 - mse: 0.5751 - val_loss: 0.4679 - val_mse: 0.4679
Epoch 4/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4624 - mse: 0.4624 - val_loss: 0.4214 - val_mse: 0.4214
Epoch 5/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4219 - mse: 0.4219 - val_loss: 0.3987 - val_mse: 0.3987
Epoch 6/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4034 - mse: 0.4034 - val_loss: 0.3846 - val_mse: 0.3846
Epoch 7/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3788 - mse: 0.3788 - val_loss: 0.3734 - val_mse: 0.3734
Epoch 8/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3773 - mse: 0.3773 - val_loss: 0.3642 - val_mse: 0.3642
Epoch 9/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3659 - mse: 0.3659 - val_loss: 0.3560 - val_mse: 0.3560
Epoch 10/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3533 - mse: 0.3533 - val_loss: 0.3492 - val_mse: 0.3492
Epoch 11/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3586 - mse: 0.3586 - val_loss: 0.3429 - val_mse: 0.3429
Epoch 12/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3501 - mse: 0.3501 - val_loss: 0.3374 - val_mse: 0.3374
Epoch 13/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3409 - mse: 0.3409 - val_loss: 0.3327 - val_mse: 0.3327
Epoch 14/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3424 - mse: 0.3424 - val_loss: 0.3284 - val_mse: 0.3284
Epoch 15/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3170 - mse: 0.3170 - val_loss: 0.3248 - val_mse: 0.3248
Epoch 16/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3270 - mse: 0.3270 - val_loss: 0.3214 - val_mse: 0.3214
Epoch 17/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3376 - mse: 0.3376 - val_loss: 0.3184 - val_mse: 0.3184
Epoch 18/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3022 - mse: 0.3022 - val_loss: 0.3158 - val_mse: 0.3158
Epoch 19/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3173 - mse: 0.3173 - val_loss: 0.3135 - val_mse: 0.3135
Epoch 20/20
360/360 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3109 - mse: 0.3109 - val_loss: 0.3117 - val_mse: 0.3117

In [24]:
mse_test = model.evaluate(X_test, y_test)

160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3189 - mse: 0.3189

In [25]:
X_new = X_test[:3]
y_pred = model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

In [27]:
scaler_y.inverse_transform(y_pred)

array([[209326.8 ],
       [152663.88],
       [204093.06]], dtype=float32)